DELETE FROM dbo.ScheduleStop
DELETE FROM dbo.Location
DELETE FROM dbo.Schedule
DELETE FROM dbo.Ferry
DELETE FROM dbo.Company

DBCC CHECKIDENT ('dbo.ScheduleStop', RESEED, 0);
DBCC CHECKIDENT ('dbo.Location', RESEED, 0);
DBCC CHECKIDENT ('dbo.Schedule', RESEED, 0);
DBCC CHECKIDENT ('dbo.Ferry', RESEED, 0);
DBCC CHECKIDENT ('dbo.Company', RESEED, 0);

INSERT INTO dbo.Company ("Name")
VALUES ('Star Ferries'),('Oceanic Ferries'),('Island Hopper Ferries'),('Harbour Link Ferries'),('Sea Breeze Ferries'),('Coastal Express Ferries'),('Marine Ferries'),('Bay Ferries'),('River Ferries'),('Island Explorer Ferries'),('Shoreline Ferries'),('High Seas Ferries'),('Wavecrest Ferries'),('Fjordline Ferries'),('Scenic Ferries'),('Sunset Ferries'),('Ocean Ferries'),('Beachcomber Ferries'),('Marine Express Ferries'),('Sea Spray Ferries'),('Island Ferry Services'),('Harbour Ferry Services'),('Bayview Ferries'),('Coastline Ferries'),('Riverfront Ferries'),('Oceanic Ferry Services'),('Star Ferry Services'),('Marine Connection Ferries'),('Bayline Ferries'),('Shoreline Ferry Services'),('Island Hopper Ferry Services'),('Harbour Link Ferry Services'),('Sea Breeze Ferry Services'),('Coastal Express Ferry Services'),('Marine Ferry Services'),('Bay Ferry Services'),('River Ferry Services'),('Island Explorer Ferry Services'),('Shoreliner Ferry Services'),('High Seas Ferry Services'),('Wavecrest Ferry Services'),('Fjordline Ferry Services'),('Scenic Ferry Services'),('Sunset Ferry Services'),('Ocean Ferry Services'),('Beachcomber Ferry Services'),('Marine Express Ferry Services'),('Sea Spray Ferry Services'),('Islander Ferry Services'),('Harbourmaster Ferry Services'),('Bayview Ferry Services'),('Coastline Ferry Services'),('Riverfront Ferry Services'),('Oceanical Ferry Services'),('Starlabs Ferry Services');

INSERT INTO dbo.Ferry ("Name", CompanyId)
VALUES ('Seaside Express', 1),
       ('Oceanic Adventurer', 2),
       ('Coastal Cruiser', 3),
       ('River Rover', 4),
       ('Harbor Explorer', 5),
       ('Island Hopper', 6),
       ('Marine Marvel', 7),
       ('Sea Spray', 8),
       ('Wave Rider', 9),
       ('Beachcomber', 10),
       ('Sunset Sailor', 11),
       ('Water Wanderer', 12),
       ('Dolphin Delight', 13),
       ('Ocean Odyssey', 14),
       ('Coastal Connection', 15),
       ('Riverside Rambler', 16),
       ('Harbor Haven', 17),
       ('Island Intrepid', 18),
       ('Marine Magic', 19),
       ('Sea Spirit', 20),
       ('Wave Watcher', 21),
       ('Beach Bum', 22),
       ('Sunset Seeker', 23),
       ('Water Wayfarer', 24),
       ('Dolphin Dreamer', 25),
       ('Ocean Outpost', 26),
       ('Coastal Companion', 27),
       ('Riverside Ramble', 28),
       ('Harbor Hero', 29),
       ('Island Insider', 30),
       ('Marine Maverick', 31),
       ('Sea Sentinel', 32),
       ('Wave Warrior', 33),
       ('Beach Buddy', 34),
       ('Sunset Safari', 35),
       ('Water World', 36),
       ('Dolphin Dancer', 37),
       ('Ocean Overlook', 38),
       ('Coastal Conquest', 39),
       ('Riverside Rambunctious', 40),
       ('Harbor Hunter', 41),
       ('Island Insight', 42),
       ('Marine Mystic', 43),
       ('Sea Sensation', 44),
       ('Wave Whimsy', 45),
       ('Beach Bazaar', 46),
       ('Sunset Seascape', 47),
       ('Water Wonderland', 48),
       ('Marina Magic', 49),
       ('Aqua Adventure', 50),
       ('Coastline Cruiser', 51),
       ('River Rambler', 52),
       ('Harbor Hop', 53),
       ('Island Explorer', 54),
       ('Sea Swirl', 55),
       ('Wave Waver', 6), 
       ('Beach Break', 7),
      ('Sunset Sailing', 8),
       ('Water Wanders', 9), 
       ('Seafaring Star', 10),
       ('Oceanic Odyssey', 1),
       ('Coastal Cruiser', 2), 
       ('River Rebel', 3),
       ('Harbor Hope', 4), 
       ('Island Intrepid', 5),
       ('Marine Marvel', 6), 
       ('Sea Spray', 7), 
       ('Wave Rider', 8), 
       ('Beachcomber', 9), 
       ('Sunset Sailor', 10),
       ('Water Wanderer', 11), 
       ('Dolphin Delight', 12), 
       ('Ocean Odyssey', 13), 
       ('Coastal Connection', 14), 
       ('Riverside Rambler', 15),
       ('Harbor Haven', 16), 
       ('Island Insight', 17), 
       ('Marine Magic', 18), 
       ('Sea Spirit', 19), 
       ('Wave Watcher', 20), 
       ('Beach Bum', 21),
       ('Sunset Seeker', 22), 
       ('Water Wayfarer', 23),
       ('Dolphin Dreamer', 24),
       ('Ocean Outpost', 25), 
       ('Coastal Companion', 26),
       ('Riverside Ramble', 27),
       ('Harbor Hero', 28), 
       ('Island Insider', 29), 
       ('Marine Maverick', 30), 
       ('Sea Sentinel', 31), 
       ('Wave Warrior', 32), 
       ('Beach Buddy', 33), 
       ('Sunset Safari', 34), 
       ('Water World', 35), 
       ('Dolphin Dancer', 36), 
       ('Ocean Overlook', 37), 
       ('Coastal Conquest', 38),
       ('Riverside Rambunctious', 39),
       ('Harbor Hunter', 40), 
       ('Island Explorer', 41), 
       ('Marine Mystic', 42), 
       ('Sea Sensation', 43), 
       ('Wave Whimsy', 44), 
       ('Beach Bazaar', 45), 
       ('Sunset Seascape', 46), 
       ('Water Wonderland', 47), 
       ('Marina Magic', 48), 
       ('Aqua Adventure', 49), 
       ('Coastline Cruiser', 50), 
       ('River Rambler', 51), 
       ('Harbor Hop', 52),
       ('Island Insight', 53),
       ('Sea Swirl', 54),
       ('Wave Waver', 55),
       ('Beach Break', 6), 
       ('Sunset Sailing', 7), 
       ('Water Wanders', 8), 
       ('Seafaring Star', 9),
       ('Oceanic Odyssey', 10),
       ('Coastal Companion', 1),
       ('River Rebel', 2), 
       ('Harbor Hope', 3), 
       ('Island Intrepid', 4), 
       ('Marine Marvel', 5), 
       ('Sea Spray', 6), 
       ('Wave Rider', 7), 
       ('Beachcomber', 8), 
       ('Sunset Sailor', 9),
       ('Water Wanderer', 10);

INSERT INTO dbo.Location ("Name")
VALUES ('Newport Harbor'), ('Cape Cod Bay'), ('Nantucket Harbor'), ('Marthas Vineyard Harbor'), ('Bar Harbor Maine'), ('Mystic River'), ('Provincetown Harbor'), ('Rockport Harbor'), ('Shelter Island Ferry Terminal'), ('Block Island Harbor'), ('Naples Marina'), ('Sorrento Port'), ('Positano Pier'), ('Amalfi Harbor'), ('Capri Marina'), ('Ischia Port'), ('Venice Marina'), ('Rome Port'), ('Florence Riverfront'), ('Pisa Marina'), ('Genoa Port'), ('Monte Carlo Harbor'), ('Nice Port'), ('Cannes Marina'), ('St. Tropez Harbor'), ('Marseille Old Port'), ('Bordeaux Riverfront'), ('Lyon Harbor'), ('Strasbourg Port'), ('Paris Seine River'), ('London Thames River'), ('Dublin Port'), ('Edinburgh Harbor'), ('Glasgow Riverfront'), ('Belfast Harbor'), ('Lisbon Port'), ('Porto Marina'), ('Funchal Harbor'), ('Barcelona Port'), ('Madrid Marina'), ('Valencia Port'), ('Seville Riverfront'), ('Malaga Marina'), ('Ibiza Port'), ('Palma de Mallorca Harbor'), ('Athens Marina'), ('Thessaloniki Port'), ('Mykonos Harbor'), ('Santorini Port'), ('Corfu Harbor'), ('Rhodes Marina'), ('Istanbul Port');

INSERT INTO dbo.Schedule (FerryId, Description, CostPerPerson, CostPerVehicle)
VALUES (1, 'Sail from Cape Cod Bay to Nantucket Harbor for a scenic trip!', 629.12, 284.52), (68, NULL, 134.96, 750.79), (86, NULL, 704.97, 28.65), (11, 'See the famous Leaning Tower of Pisa on a ferry ride from Genoa Port!', 66.41, 984.92), (55, NULL, 814.96, 609.53), (15, 'Discover the rich history of Lyon on a 
ferry ride from Strasbourg Port!', 194.29, 634.04), (10, 'Admire the beautiful architecture of Florence on a ferry ride from the citys riverfront!', 446.55, 
636.37), (85, NULL, 474.48, 489.8), (57, NULL, 922.86, 82.13), (20, 'Take 
a trip to the charming city of Lisbon on a ferry ride from Porto Marina!', 611.55, 573.6), (13, 'Enjoy the luxurious beaches of Cannes with a ferry ride from 
St. Tropez Harbor!', 274.87, 160.33), (66, NULL, 177.12, 848.32), (95, NULL, 663.29, 872.52), (51, NULL, 474.48, 489.8), (2, 'Experience the beauty of New England with a ferry ride from Bar Harbor Maine to Block Island Harbor!', 814.96, 609.53), (23, 'Take a trip to the vibrant city of Valencia on a ferry ride from Madrid Marina!', 809.43, 980.9), (13, 'Enjoy the luxurious beaches of Cannes with a ferry ride from St. Tropez Harbor!', 274.87, 160.33), (17, 'See the famous landmarks of London with a ferry ride along the Thames River!', 406.36, 441.59), (44, NULL, 86.34, 538.89), (63, NULL, 454.3, 701.73), (69, NULL, 274.18, 617.02), (43, NULL, 421.39, 460.73), (93, NULL, 123.64, 738.13), 
(59, NULL, 9.29, 316.61), (49, NULL, 13.33, 217.68), (19, 'Explore the vibrant city of Glasgow with a ferry ride from Belfast Harbor!', 177.12, 848.32), (20, 'Take a trip to the charming city of Lisbon on a ferry ride from Porto Marina!', 611.55, 573.6), (17, 'See the famous landmarks of London with a ferry ride along the Thames River!', 406.36, 441.59), (84, NULL, 66.41, 984.92), (12, 'Take a trip to the glamorous city of Monte Carlo on a ferry ride from Nice Port!', 457.94, 934.25), (13, 'Enjoy the luxurious beaches of Cannes with a ferry ride from St. Tropez Harbor!', 274.87, 160.33), (73, NULL, 221.08, 157.19), (123, NULL, 679.11, 318.05), (66, NULL, 86.34, 538.89), (91, NULL, 86.34, 
538.89), (18, 'Discover the rich history of Dublin on a ferry ride from Edinburgh Harbor!', 691.21, 346.56), (62, NULL, 691.21, 346.56), (113, NULL, 328.88, 665.79), (43, NULL, 421.39, 460.73), (67, NULL, 572.59, 431.73), (118, 
NULL, 546.41, 61.95), (5, 'Relax on a ferry ride from Shelter Island Ferry Terminal to Greenport Village!', 893.4, 684.13), (31, 'Relax in the sun-soaked town of Santorini with a ferry ride from Athens Marina!', 220.15, 993.15), (67, 
NULL, 177.12, 848.32), (117, NULL, 546.41, 61.95), (113, NULL, 406.36, 441.59), (107, NULL, 359.69, 424.53), (87, NULL, 691.21, 346.56), (38, 'Take a 
trip to the vibrant city of Belfast on a ferry ride from Dublin Port!', 644.16, 
114.94), (46, NULL, 9.29, 316.61)

INSERT [dbo].[ScheduleStop] (ScheduleId, LocationId, DepartureDay, DepartureTime, ArrivalDay, ArrivalTime)
VALUES (1, 2, 0, CAST(N'08:00:00' AS Time), 0, CAST(N'08:00:00' AS Time)),
       (1, 3, 2, CAST(N'16:00:00' AS Time), 2, CAST(N'12:00:00' AS Time))
