//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Sightings = new HashSet<Sighting>();
        }
    
        public int CarId { get; set; }
        public string RegistrationNumber { get; set; }
        public int ColourId { get; set; }
        public int ModelId { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public int OwnerId { get; set; }
    
        public virtual Colour Colour { get; set; }
        public virtual Model Model { get; set; }
        public virtual Owner Owner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sighting> Sightings { get; set; }
    }
}
