//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenceCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LicenceCategory()
        {
            this.LicenceEntitlements = new HashSet<LicenceEntitlement>();
        }
    
        public int LicenceCategoryId { get; set; }
        public int MinimumAge { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LicenceEntitlement> LicenceEntitlements { get; set; }
    }
}
