//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sighting
    {
        public int SightingId { get; set; }
        public int CarId { get; set; }
        public int CameraId { get; set; }
        public System.DateTime SightingTime { get; set; }
        public Nullable<byte> SecondsAfterRedLight { get; set; }
        public Nullable<byte> SpeedMph { get; set; }
    
        public virtual Camera Camera { get; set; }
        public virtual Car Car { get; set; }
        public virtual Fine Fine { get; set; }
    }
}
