//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataAccessModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverJourney
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DriverJourney()
        {
            this.JourneyStops = new HashSet<JourneyStop>();
        }
    
        public int DriverJourneyId { get; set; }
        public int DriverId { get; set; }
        public System.DateTime Date { get; set; }
        public int SeatsAvailable { get; set; }
        public byte[] RowVersion { get; set; }
        public bool FromToWork { get; set; }
        public System.TimeSpan LeavingTime { get; set; }
        public bool IsLocked { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JourneyStop> JourneyStops { get; set; }
    }
}
