//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataAccessModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class JourneyStop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JourneyStop()
        {
            this.PassengerJourneys = new HashSet<PassengerJourney>();
        }
    
        public int JourneyStopId { get; set; }
        public int LocationId { get; set; }
        public int DriverJourneyId { get; set; }
        public int TimeFromHome { get; set; }
    
        public virtual DriverJourney DriverJourney { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PassengerJourney> PassengerJourneys { get; set; }
    }
}
