//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataAccessModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengerJourney
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PassengerJourney()
        {
            this.Notifications = new HashSet<Notification>();
        }
    
        public int PassengerJourneyId { get; set; }
        public int JourneyStopId { get; set; }
        public int StatusId { get; set; }
        public byte[] RowVersion { get; set; }
        public int PassengerId { get; set; }
    
        public virtual JourneyStop JourneyStop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual PassengerJourneyStatus PassengerJourneyStatus { get; set; }
        public virtual User User { get; set; }
    }
}
